#!/bin/bash

set -e

usage() {
    cat <<EOM
usage: $(basename $0) <commitish>
  Checks out commitish in OUTPUT_DIR ("$OUTPUT_DIR")
  OUTPUT_DIR defaults to "$DEFAULT_OUTPUT_DIR" if the environment variable is not set.
EOM
    exit 0
}

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/constants > /dev/null

[ -z $1 ] && { usage; }

COMMITISH=$1

echo "Checking out $COMMITISH into directory $OUTPUT_DIR"
#git -C $OUTPUT_DIR fetch || git clone $ROOT_DIR $OUTPUT_DIR
git -C $OUTPUT_DIR checkout $COMMITISH
