#!/bin/bash

ROOT_DIR="$(dirname "$(dirname "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )")")"
DEFAULT_OUTPUT_DIR=$HOME/.report-card-perfetto
OUTPUT_DIR=$HOME/.report-card-perfetto

echo root_dir: $ROOT_DIR
echo default_output_dir: $ROOT_DIR
echo output_dir: $ROOT_DIR
