const categories = [
  { tag: "gfx",        name: "Graphics"},
  { tag: "input",      name: "Input"},
  //  { tag: "view",       name: "View System"},
  //  { tag: "webview",    name: "WebView"},
  //  { tag: "wm",           name: "Window Manager"},
  //  { tag: "am",         name: "Activity Manager"},
  //  { tag: "sm",         name: "Sync Manager"},
  //  { tag: "audio",      name: "Audio"},
  //  { tag: "video",      name: "Video"},
  //  { tag: "camera",     name: "Camera"},
  //  { tag: "hal",        name: "Hardware Modules"},
  //  { tag: "res",        name: "Resource Loading"},
  //  { tag: "dalvik",     name: "Dalvik VM"},
  //  { tag: "rs",         name: "RenderScript"},
  //  { tag: "bionic",     name: "Bionic C Library"},
  //  { tag: "power",      name: "Power Management"},
  //  { tag: "pm",         name: "Package Manager"},
  //  { tag: "ss",         name: "System Server"},
  //  { tag: "database",   name: "Database"},
  //  { tag: "network",    name: "Network"},
  //  { tag: "adb",        name: "ADB"},
  //  { tag: "vibrator",   name: "Vibrator"},
  //  { tag: "aidl",       name: "AIDL calls"},
  //  { tag: "nnapi",      name: "NNAPI"},
  { tag: "core_services", name: "Core services"},
  { tag: "pdx", name: "PDX services"},
  { tag: "sched",      name: "CPU Scheduling"},
  //  { tag: "irq",        name: "IRQ Events"},
  //  { tag: "irqoff",     name: "IRQ-disabled code section tracing"},
  //  { tag: "preemptoff", name: "Preempt-disabled code section tracing"},
  //  { tag: "i2c",        name: "I2C Events"},
  //  { tag: "freq",       name: "CPU Frequency"},
  //  { tag: "membus",     name: "Memory Bus Utilization"},
  //  { tag: "idle",       name: "CPU Idle"},
  //  { tag: "disk",       name: "Disk I/O"},
  //  { tag: "mmc",        name: "eMMC commands"},
  //  { tag: "load",       name: "CPU Load"},
  //  { tag: "sync",       name: "Synchronization"},
  //  { tag: "workq",      name: "Kernel Workqueues"},
  //  { tag: "memreclaim", name: "Kernel Memory Reclaim"},
  //  { tag: "regulators",  name: "Voltage and Current Regulators"},
  //  { tag: "binder_driver", name: "Binder Kernel driver"},
  //  { tag: "binder_lock", name: "Binder global lock trace"},
  //  { tag: "pagecache",  name: "Page cache"},
];

export {
  categories,
};
