#!/bin/bash
# Copyright (C) 2018 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

readonly ROOT_DIR="$(dirname $(cd -P ${BASH_SOURCE[0]%/*}; pwd))"

if [ ! -z "$(git status --porcelain)" ]; then
  echo "Working directory not clean!"
  exit 1
fi
if [ $# -ne 1 ]; then
  echo "Set out directory!"
  exit 1
fi

readonly BRANCH=$(git rev-parse --abbrev-ref HEAD)
readonly OUT_DIR=$1

cd $ROOT_DIR
rm -rf $OUT_DIR/ui/*
ninja -C $OUT_DIR ui
git checkout site
cp -r $OUT_DIR/ui/* .
git add --all
git commit -m'publish'
git push -u perfetto-ui-site site:master
git checkout $BRANCH
